### ISSUE TITLE
Add ability commands to right hand pane, rather than right clicking on Tree View

### ISSUE THREAD

**Issue by daryllabar** [Cinteros/FetchXMLBuilder#100]
It feels a little awkward to constantly be right clicking on the tree view to add conditions/filters/ etc.  There should be an option to perform these actions right from the right hand pane, when in the context of a node on the tree.

Can you add buttons to the right hand pane to handle this?

**Comment by pieeetr** [comment]
Agree!

**Comment by rappen** [comment]
How about something like this?
Buttons appear with context awareness of the selected node.

![image](https://cloud.githubusercontent.com/assets/2572253/12510822/e8d19fd2-c10c-11e5-85ad-11a3c7a1b5b3.png)

**Comment by daryllabar** [comment]
That would work.  I'm wondering if it makes more sense to be at the top, to minimize mouse travel...  Could also make icons and put them vertical, then you could access them from either side with ease

**Comment by pieeetr** [comment]
I agree with Daryl. On top would be very nice.
fre 22 jan. 2016 kl. 14:06 skrev Daryl LaBar <notifications@github.com>:

**Comment by rappen** [comment]
Better?

![image](https://cloud.githubusercontent.com/assets/2572253/12515403/8ba74d22-c128-11e5-811a-9bba10e60559.png)

**Comment by daryllabar** [comment]
IMHO yes!  Do you want me to try and find some icons that you can use instead?  Might look a little less cluttered...

**Comment by rappen** [comment]
@daryllabar not really supported by the architecture at the moment - but sure!
Would of course be great :)

Available "add" items are listed by parent node type here: https://github.com/Cinteros/FetchXMLBuilder/blob/master/FetchXmlBuilder/AppCode/FetchNodeCapabilities.cs

**Comment by daryllabar** [comment]
@rappen I meant the new Tool bar you created.  Rather than text, I think it would look better as buttons, with the text as tooltips on the buttons
![8ba74d22-c128-11e5-811a-9bba10e60559](https://cloud.githubusercontent.com/assets/9728423/12554360/16f91f7c-c34a-11e5-8efd-8e69cef80f4d.png)

**Comment by rappen** [comment]
Absolutely, I agree :)
What I meant is that the code supporting generalized context aware add actions does not support "image" property as of now. But it could be added.

**Comment by daryllabar** [comment]
Oh, I thought you were talking about the tree node itself
