### ISSUE TITLE
OData Converter Doesn't Append Top # Parameter 

### ISSUE THREAD

**Issue by daryllabar** [Cinteros/FetchXMLBuilder#102]
I changed the fetch xml to only return one record, and it didn't add the $top=1 filter

**Comment by rappen** [comment]
The ``$top`` parameter is associated with the ``Top`` attribute in the fetch.
Do you think it makes more sense to associate it with the ``Count`` attribute?

![image](https://cloud.githubusercontent.com/assets/2572253/12508404/08067eb0-c0fc-11e5-93ad-85713d0d8ca5.png)

**Comment by daryllabar** [comment]
So the count is the number of results to return, and the top is where to start from?

**Comment by rappen** [comment]
No, not really, unless I am mistaken...
Top is "I am only interested in the first x records".
Count is "I want them all, but please page them so I only get x at a time".

**Comment by daryllabar** [comment]
So I changed the count to 1, and got 1 back, but it wouldn't filter the top, since I didn't enter a value in for top?  If that's the case, I'd take the lesser of either one, since then the number of results the fetch XML and OData returns will be the same that way (assuming < 50)

**Comment by rappen** [comment]
Not sure I am following you entirely...
But for CRM OData endpoint, Count is hard coded by MS to 50, we can't change that. It will specify the page size (for fetch gives same result as Top, but you also get a paging cookie to get next page).
Setting Top will not give you the cookie, just the first x records.
I also noticed that combining the two in a fetch is not allowed by the SDK.
And $count is not supported for CRM, as stated here https://msdn.microsoft.com/sv-se/library/gg309461(v=crm.7).aspx#BKMK_top

**Comment by daryllabar** [comment]
Ideally the user would be smart enough to know to use top, rather than count, but it is pretty easy to see count, and edit that, thinking it's going to limit your Rest Call.  And then to compound the problem, when you run the query, the Results will be limited to the amount listed in the count for the Fetch call, but not for the Rest call, since you have to use Top for that.  If someone has entered 1 for Count, it is pretty good bet, (when needing to generate the Rest Call) that they really meant top, so it would be a nice feature to use whatever value is smaller, top or Count, as the top, unless it's 50 or greater.  Then the results of the Fetch XML query, would match the results of the Rest query.

Or you could just call it a training issue and move on :)

**Comment by rappen** [comment]
Again, I agree... :)
However, it could be a dangerous path to walk down, starting to assume what the user really wants, to compensate for possible flaws in the SDK/REST implementation...
I am considering some "smart help" functionality, e.g. removing ``values`` when condition operator is not ``in`` (#101), removing attribute aliases for non-aggregate queries (#60), and this one... I think those thoughts need to mature a bit in my head :)

**Comment by rappen** [comment]
Closing this, refer to issue #106
