### ISSUE TITLE
CRM navigation in Result Grid

### ISSUE THREAD

**Issue by shytikov** [Cinteros/FetchXMLBuilder#112]
It would be nice if double click on cell in Result grid that represents entity reference would lead to opening referenced records in same or new Result Grid.

Maybe not by double click, but via right click menu, but it would be very handy to be able explore linked entities right from `FXB`

**Comment by rappen** [comment]
Should it just fetch that record with all attributes?
Not sure that is what you want, but definitely clicking on an entityreference field could open that record in the connected CRM, just like double-clicking a record row in the result grid!

**Comment by rappen** [comment]
Feature that will be implemented:
![image](https://cloud.githubusercontent.com/assets/2572253/13527920/0627839a-e213-11e5-89a5-ecfe79492bc1.png)

This makes it possible to click on a value that is an ``EntityReference`` (lookup field) to open that parent record.
Functionality to double click a row to open the record is still available too.
