### ISSUE TITLE
Cannot find version of McTools.Xrm.Connection 

### ISSUE THREAD

**Issue by mscottsewell** [Cinteros/FetchXMLBuilder#117]
I just create a fresh install of the latest XRMToolbox (v1.2016.2.28) and downloaded the current FXB (1.2016.1.93)
![2016-02-29_21-41-05](https://cloud.githubusercontent.com/assets/6276300/13416107/1fbea1e0-df2e-11e5-9356-56f5cc2f0edd.png)

and it's failing when I launch it with this error - 
An error occured when trying to display this plugin: Could not load file or assembly 'McTools.Xrm.Connection, Version=1.2016.1.7 ... The system cannot find the file specified.

![2016-02-29_21-41-19](https://cloud.githubusercontent.com/assets/6276300/13416100/102a167e-df2e-11e5-9de5-916520ab4b9d.png)

**Comment by shytikov** [comment]
I also noticed that error yesterday. I believe recompile with most recent `XTB` dependencies updated should fix the issue.

I will try to trigger pre-release build on CI with fix if Jonas won't do this faster ;)

**Comment by rappen** [comment]
Please try, I'm on vacation! :)

**Comment by liorabel** [comment]
CRM Toolbox changed how connections are handled. As of version 1.2016.1.93 of FetchXml Builder, this is not yet reflected. It won't work until updated.

**Comment by shytikov** [comment]
Hi guys!

Here is an official pre-release of `FetchXML` Builder supporting `XrmToolBox 1.2016.2.28`: [binary download](https://github.com/Cinteros/FetchXMLBuilder/releases/download/1.2016.3.95/FetchXMLBuilder_1.2016.3.95.zip).

**Comment by mscottsewell** [comment]
This works for me again - 
Thanks! -

**Comment by shytikov** [comment]
@mscottsewell glad to hear!

I'm not closing this one so far. Let Jonas decide how to handle this properly.

**Comment by rappen** [comment]
Thanks @shytikov, my wing man! ;)

**Comment by rappen** [comment]
Fixed by @shytikov in #117.

**Comment by zmulk** [comment]
I downloaded the newest file from XRMtoolbox and the newest from FetchXML builder, still I do get this error.

**Comment by rappen** [comment]
Please see solution/workaround descriped in #120.

**Comment by zmulk** [comment]
Is this going to be fixed, so we don't need to have a workaround.
btw thanks it works now for me

**Comment by rappen** [comment]
Yes, this will be fixed for future releases of XrmToolBox so that all plugins expecting a specific version of related assemblies are "excused".
