### ISSUE TITLE
Error loading plugin: Could not load file or assembly 'McTools.Xrm.Connection' version=1.2016.2.28

### ISSUE THREAD

**Issue by readyxrm** [Cinteros/FetchXMLBuilder#120]
Getting the attached error "Could not load file or assembly 'McTools.Xrm.Connection' version=1.2016.2.28"

Using XrmToolBox 1.2016.3.29
Using FetchXMLBuilder 1.2016.3.96

![2016-04-04_10-07-08](https://cloud.githubusercontent.com/assets/18264651/14250731/c4a28cd2-fa4d-11e5-89f7-88fc83a4e4c8.png)

**Comment by rappen** [comment]
This is a known issue when using *not-entirely-compatible* versions of XrmToolBox and FetchXML Builder.
It is easily resolved by opening file ``XrmToolBox.exe.config`` file in the XrmToolBox folder, locating the highlighted commented section below:
![image](https://cloud.githubusercontent.com/assets/2572253/14251793/dfadcc26-fa84-11e5-9ec7-81ca8aea8f1c.png)

Then follow the advice in the file and un-comment that block, which will give you this appearance:
![image](https://cloud.githubusercontent.com/assets/2572253/14251819/f61cc746-fa84-11e5-93af-7a7714b3e2d2.png)

Now it should be possible to run all plugins expecting a slightly older version of ``McTools.Xrm.Connection.dll``.

**Comment by readyxrm** [comment]
Thanks for the super fast response!  This fixed the issue for me.
Cheers
Nick
