### ISSUE TITLE
Move FetchRequest to output options

### ISSUE THREAD

**Issue by rappen** [Cinteros/FetchXMLBuilder#15]
Selecting _FetchRequest_ or _RetrieveMultiple_ when executing does not really make sense anymore.
Easier if that is moved to Output Options along with the other options:
* Serialized XML
* JSON
* Grid
* FetchResult

![image](https://cloud.githubusercontent.com/assets/2572253/6351486/5359b10e-bc3c-11e4-9bd7-26b74b8c2c9a.png)

**Comment by pieeetr** [comment]
It would also be nice to have a shortcut to run the FetchXML query with the default option, SQL Management Studio Style, [F5] for example.

**Comment by shytikov** [comment]
:+1:

**Comment by rappen** [comment]
@pieeetr This is handled in issue #18.
