### ISSUE TITLE
Query output type should have default value in drop-down menu

### ISSUE THREAD

**Issue by shytikov** [Cinteros/FetchXMLBuilder#19]
During **very first run** when output type is not set, so trying execute query leads to notification message, asking to select desirable output type.

It confuses new user (as only very new users will receive such message) and makes them roam around to find needed option to set.

I think it's possible to stick to any `output type` value (presumably first one) as default to not confuse new users.

**Comment by rappen** [comment]
:+1:

**Comment by rappen** [comment]
Fixed #19
