### ISSUE TITLE
Change namespace

### ISSUE THREAD

**Issue by rappen** [Cinteros/FetchXMLBuilder#2]
Might be a good idea to have namespace:

`Cinteros.XrmToolbox.<pluginname>`

for all XrmToolbox plugins from Cinteros.

**Comment by shytikov** [comment]
Where is annoying typo in name XrmTool**b**ox instead of XrmTool**B**ox...

And in addition if we will rename to XrmTool**B**ox we will conflict with original tool namespace...

How about `Cinteros.XTB.<pluginname>` or `XrmToolBox.Cinteros.<pluginname>` ?

**Comment by rappen** [comment]
I was just following the naming at codeplex... lowercase "b" there...
But then I have seen him writing with capital "B" also...
*confused*

**Comment by shytikov** [comment]
I think we need to follow `XrmToolBox` plugins convention. 

Most plugins are like this: `MsCrmTools.AccessChecker`, i.e. `<CompanyName>.<PluginName>`.

In case of `Javista.XrmToolBox.ImportNN` capital **B** was used...

I would prefer first approach. My argumentation:
* most plugins are already using it;
* there is no interference with main `XrmToolBox` plugin namespace.

**Comment by rappen** [comment]
I agree.
However, if I update to new file name and users deploy that from the zip, two editions of FXB will be shown, as the old file is still there. That does not look good.
I have also verified, mr T prefers uppercase B.
By the way - are we talking about assembly name and/or namespace?

**Comment by shytikov** [comment]
So final version is `Cinteros.Xrm.FetchXmlBuilder`?

**Comment by rappen** [comment]
Final version is - I don't change existing namespace due to the duplicated plugin scenario at end users...
