### ISSUE TITLE
List of Entities / Views in FXB is not refreshed until XrmToolbox is closed / re-opened

### ISSUE THREAD

**Issue by mscottsewell** [Cinteros/FetchXMLBuilder#21]
When the FXB "Open View" option is accessed the first time, FXB retrieves and caches a list of available entities/views.
If a new view is added to CRM, it won't show up in the list of available views until the Toolbox is closed / reopened (just closing/reopening the FXB tab is not enough)
If the connection is changed from one organization to another, the first organization's views will remain cached until the toolbox is closed and re-opened.

**Comment by rappen** [comment]
I will change it to force reload after connection change, and a refresh-button in the dialog to update manually on demand.
