### ISSUE TITLE
Add version checking to the FXB tab 

### ISSUE THREAD

**Issue by mscottsewell** [Cinteros/FetchXMLBuilder#22]
Not sure if you can do a runtime check of the installed vs. latest version from with the tab, but that would be helpful to ensure that I'm up-to-date with changes that you release.
At minimum, add a hyperlink to your github releases page in the 'about' menu to make it easy to compare versions while in the tool.

**Comment by rappen** [comment]
Great suggestion!
There is a quite extensive discussion/issue for XTB concerning this MscrmTools/XrmToolBox#59
Initiated by me last night...
If that does not come to a simple and fast generic solution, I will add my own solution.
