### ISSUE TITLE
Info/Warning message for Aggregate queries should be more informative

### ISSUE THREAD

**Issue by rappen** [Cinteros/FetchXMLBuilder#25]
When creating aggregate queries, it is not possible to convert these to QueryExpression, and when executing the query the user is only informed this is not possible.
Add information why, and how to get around it.
![image](https://cloud.githubusercontent.com/assets/2572253/6622025/46d31c5e-c8da-11e4-9a71-48b51e13f7d6.png)

**Comment by pieeetr** [comment]
Maybe even give user a hint as soon as aggregate checkbox is checked.
