### ISSUE TITLE
Check Organisation Version

### ISSUE THREAD

**Issue by rajyraman** [Cinteros/FetchXMLBuilder#30]
With Spring '15 Update there is going to be a mismatch between OnPrem and Online and hence we should be checking if the fetch statement/condition is supported for the organisation version. There are new condition operators for Datetime and this is Online only at the moment.

https://msdn.microsoft.com/en-us/library/gg334216.aspx

**Comment by rappen** [comment]
:+1:

**Comment by MscrmTools** [comment]
Please note that ConnectionDetail object available in all XrmToolBox plugins provide OrganizationMajorVersion and OrganizationMinorVersion to determine the version of CRM connected

**Comment by rappen** [comment]
Thanks!

**Comment by rappen** [comment]
Closing this, refer to issue #106
