### ISSUE TITLE
Opening the view "Accounts : No Orders in Last 6 Months" crashes the app.

### ISSUE THREAD

**Issue by mscottsewell** [Cinteros/FetchXMLBuilder#33]
The "Accounts : No Orders in Last 6 Months"  view doesn't open correctly - (It's an out of the box view.) 

I've tested with CRM2015 OnPremise and CRM2015 Online Beta and in both cases, attempting to open the view, the app throws an exception. 

*System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Cinteros.Xrm.FetchXmlBuilder.FetchXmlBuilder.OpenView()*

FXB Version 1.2015.3.13

**Comment by mscottsewell** [comment]
This appears to be a 'special' view delivered out of the box - it doesn't follow the same pattern as the other OOB provided views. The filter is not editable/viewable within CRM.  
Ultimately, it may be unwise to attempt to customize it - I was just viewing it to see how they built that view. - Regardless, you'll want to avoid the exception. :)

**Comment by rappen** [comment]
@mscottsewell Fix for this is now released in the new version.
