### ISSUE TITLE
Read metadata using MetadataQueryExpression

### ISSUE THREAD

**Issue by rappen** [Cinteros/FetchXMLBuilder#35]
https://msdn.microsoft.com/en-us/library/microsoft.xrm.sdk.metadata.query.metadataqueryexpression(v=crm.7).aspx
Apparently a lot more efficient, according to @mscrmtools http://crmtipoftheday.com/2015/03/31/retrieve-only-metadata-you-need/

**Comment by MscrmTools** [comment]
Absolutely, you can retrieve only few metadata, the one you really need!

I should update all my tools that use metadata too :)
