### ISSUE TITLE
Convert to OData

### ISSUE THREAD

**Issue by rappen** [Cinteros/FetchXMLBuilder#4]
Add function to convert FetchXML to OData query string, when possible depending of the complexity of the FetchXML.

**Comment by shytikov** [comment]
Voting for this one very much :+1: :smile:

**Comment by MscrmTools** [comment]
:+1:

**Comment by pieeetr** [comment]
Voting super much as well!

**Comment by soderstam** [comment]
:thumbsup:

**Comment by filcole** [comment]
:+1:

**Comment by rappen** [comment]
For those who would to try a beta version of the OData generation, download prerelease here:
https://github.com/Cinteros/FetchXMLBuilder/releases/tag/1.2015.10.68


**Select option** ``Show OData Equivalent``

![image](https://cloud.githubusercontent.com/assets/2572253/10691201/b514d618-7987-11e5-85cf-a8c45d58867c.png)


At the bottom the **url will be displayed** and updated on the fly as you build your query. **Click** the url to open the query in a browser, och right click to copy the url.

![image](https://cloud.githubusercontent.com/assets/2572253/10691304/592cdae8-7988-11e5-9872-a35f22b66734.png)

**This beta is published for feedback on functionality. It still lacks support for link-entities, some condition operators etc.**

**Comment by shytikov** [comment]
Our lives won't be the same anymore!
