### ISSUE TITLE
Issue using FetchXMLBuilder with CRM 2011

### ISSUE THREAD

**Issue by David1610** [Cinteros/FetchXMLBuilder#46]
The tool works really well for CRM 2015, but when I try to use it for CRM 2011, it gives me an error. I am trying to return all the accounts which have no contacts. The error states " 'Account' entity doesn't contain attribute with Name = 'contactid'. "
Is the tool meant to work with CRM 2011? Or am I doing something wrong?

**Comment by rappen** [comment]
Hi David!
Outer joins and aliased conditions were introduced in CRM 2013, so unfortunately this is not supported in CRM 2011.

**Comment by David1610** [comment]
Thanks Jonas, I appreciate the quick response.

David Mochrie
Business Consultant
Adaptable Solutions
ddi: +64 9 302 6231 | mobile: +64 27 286 7504 |  office: +64 9 523 2405 [Linkedin Icon] <https://www.linkedin.com/company/adaptable-solutions-ltd.>   [YouTube icon] <https://www.youtube.com/user/AdaptableSolutions>   [Blog Icon] <http://www.adaptable.co.nz/Blog>   [Twitter Icon] <https://twitter.com/adaptable_nz>
[2015 Email Signature Block Image]<http://www.adaptable.co.nz/>
