### ISSUE TITLE
Configure CWP substitution parameters in Query

### ISSUE THREAD

**Issue by rappen** [Cinteros/FetchXMLBuilder#5]
Add a user-friendly possibility to be able to in the FetchXml-builder specify that an attribute in the FetchXml query - when saved to CRM as a CWP feed - should be replaced with a specific CWP substitution parameter. 

For example `{cwpuser:contact_id}` in the cwpuser namespace, or `{querystring:myQueryStringVariable}` in the querystring-namespace.

Example of a resulting FetchXml feed saved to CRM:
```
<fetch mapping="logical" version="1.0">
  <entity name="cint_cwp_login">
    <attribute name="cint_username" />
    <attribute name="cint_cwp_loginid" />
        <filter>
            <condition attribute="cint_username" operator="eq" value="{cwpuser:name}" />
        </filter>
  </entity>
</fetch>
```
Another example:
```
<fetch mapping="logical" version="1.0">
  <entity name="cint_cwp_login">
    <attribute name="cint_username" />
    <attribute name="cint_cwp_loginid" />
        <filter>
            <condition attribute="cint_username" operator="eq" value="{querystring:username}" />
        </filter>
  </entity>
</fetch>
```

**Comment by adner** [comment]
Suggest closing this one without action. After giving it some thought, I think this functionality is too narrow in scope and specialized to be part of the standard tool. Could perhaps be part of some kind of cwp-enhancement to the fetchxmltoolkit?

**Comment by rappen** [comment]
:+1:
