### ISSUE TITLE
Minimize/restore Live XML with XTB main window

### ISSUE THREAD

**Issue by rappen** [Cinteros/FetchXMLBuilder#53]
If the Live XML Update window is open and XTB is minimized, the LiveXML is still visible.

Probably need a window event from main form to hook into.
@mscrmtools might that be possible?

**Comment by MscrmTools** [comment]
You should be able to access Main XrmToolBox app with something like this.ParentForm then register for the event when the form is minimized, no?

**Comment by rappen** [comment]
I will try! :+1:
