### ISSUE TITLE
OOB Entities are not shown in the 'Open/View' Select view dialog.

### ISSUE THREAD

**Issue by mscottsewell** [Cinteros/FetchXMLBuilder#57]
I don't see any OOB entites, only the custom entities - not sure if this is intended or a bug, but I would really like to select views from OOB entities.

(This is a CRM 2015 Spring (7.1) online environment)

**Comment by rappen** [comment]
I would guess that is related to this known bug:
http://fxb.xrmtoolbox.com/#comment-2030157287

If not - let me know!

**Comment by rappen** [comment]
Will be fixed in #55

**Comment by mscottsewell** [comment]
That's the answer - thanks. - 
I must have set that filter at some point - I forgot that the option was even there.

**Comment by rappen** [comment]
:+1:

**Comment by mscottsewell** [comment]
Thanks again! - it's a fantastic tool! - - :clap:
