### ISSUE TITLE
Copy Results

### ISSUE THREAD

**Issue by not-in-service** [Cinteros/FetchXMLBuilder#70]
Is there a way to copy the results of a FetchXMLBuilder query or export them to another format?  I'm sorry if this is a dumb question, but I have no problem selecting all the rows in the "ResultsGrid" but it doesn't seem like copying or exporting from there is an option.

Thank you!

**Comment by rappen** [comment]
Issue #48 is about the same problem.
Until then, execute with XML or JSON results is the best option, which I realize is not very good...
