### ISSUE TITLE
datagridview to listview c#

### ISSUE THREAD

**Issue by fthplt58** [Cinteros/FetchXMLBuilder#77]
Hi. I want to transfer all informations at DataGridview To Listview on my windows form application at C Sharp.
But i have no idea this solution. Please can you help me?

**Comment by rappen** [comment]
Can you please tell me how this relates to FetchXML Builder?
Then I might have a chance to help you.

**Comment by fthplt58** [comment]
![image](https://cloud.githubusercontent.com/assets/13535869/9250465/d0a63fbe-41d5-11e5-9f11-d13ec1102205.png)

i will choose a excel file after these datagridview afterthat listview

**Comment by rappen** [comment]
I repeat:

Can you please tell me how this relates to __FetchXML Builder__ ?
Then I might have a chance to help you.

**Comment by fthplt58** [comment]
FetchXML Builder ? i don't know. i don't understand you.

**Comment by rappen** [comment]
Check which project you are in. This is FetchXML Builder on github.
Closing the issue, hope you find the right place to ask these questions.
