### ISSUE TITLE
Disable / Enable FetchXML conditions / attributes `on-fly`

### ISSUE THREAD

**Issue by shytikov** [Cinteros/FetchXMLBuilder#80]
It would be nice to be able disable and re-enable FetchXML conditions on fly, and include or exclude attributes from results in the same manner.

I'm talking about behavior like `PluginRegistration` has. If I don't want plugin step to fire, but I think I might still need it, I can simply disable it for now. The same should be possible for conditions in FetchXML.

For example, I'm debugging FetchXML, or just digging the data, or trying understand, is this condition is needed or not, I should be able to temporarily disable it, run query, check result, and than decide should I delete this condition or should I keep it.

The same scenario might be usable for attributes as well. 

In theory, we can store `enable` / `disable` status in FetchXML comments. So disabled statement just becomes commented out. But still remains in the file, until user decides to throw it away completely.

**Comment by rappen** [comment]
Do you need anything more than what #59 introduced?
You even have shortcuts ctrl+K and ctrl+U.

**Comment by shytikov** [comment]
Cool, looks like what I need, sorry for opening duplicate.
