### ISSUE TITLE
Selecting `grouping` items in link-entity Relationship comboboxes leads to error

### ISSUE THREAD

**Issue by shytikov** [Cinteros/FetchXMLBuilder#83]
If just by accident one of these items `1:M` or `M:1` or others become selected, for example while pressing arrow down on keyboard on this screen:

![1m](https://cloud.githubusercontent.com/assets/1185905/10014601/b687bc20-611a-11e5-8d9b-0027d8dc27a6.png)

Very unpleasant exception shows up:

![1m_exception](https://cloud.githubusercontent.com/assets/1185905/10014658/2638f41c-611b-11e5-8d63-2018be943500.png)

Not a big deal, could be dismissed, but a bit scary for eyas mind like mine.

**Comment by rappen** [comment]
Aouch.
