### ISSUE TITLE
Clear OData Url on unsupported fetchxml

### ISSUE THREAD

**Issue by rajyraman** [Cinteros/FetchXMLBuilder#88]
It would be great if the Odata Url is cleared or a message displayed when the fetchxml change can no longer produce valid OData Url. Eg. From a routine fetch to an aggregate fetch

**Comment by rappen** [comment]
So it does.... like this for example:
![image](https://cloud.githubusercontent.com/assets/2572253/10903066/0c978738-8206-11e5-8a99-b1391dade9d8.png)

But most certainly there are cases still missing, for instance having an aggregate query (which I definitly should have handled)

Please add other invalid fetch scenarios here if you find any, so I can handle those as well! :)

**Comment by rappen** [comment]
@rajyraman Any more info on this?

**Comment by rappen** [comment]
Closing as no new info has been supplied.
