### ISSUE TITLE
New version of XRM tool Box

### ISSUE THREAD

**Issue by eblanchetip** [Cinteros/FetchXMLBuilder#90]
Hi,
The FetchXMLBuilder plugin does no appear on my new verson of XRMToolBox.
Maybe your plugin should be migrated ? Or is the problem on my side ?

Thank you for your help ! :-)

**Comment by rappen** [comment]
Hi,
FXB is in sync with XrmToolBox.
Make sure you have latest version of both, and that the FXB files are placed in the ``Plugins`` subfolder.
Current version of XrmToolBox is ``1.2015.11.5``
FetchXML Builder is ``1.2015.10.72``

**Comment by eblanchetip** [comment]
You are right, everything is fine. Thank you !
