### ISSUE TITLE
Cut and Paste/Export Support for Results

### ISSUE THREAD

**Issue by smgtreker** [Cinteros/FetchXMLBuilder#95]
Hi,

Love your tool; use it every day! Would it be possible to have support to export the results of the query, or cut and paste support?

I added something like the following to add cut and paste support and seemed to work well:

     private void lvGrid_KeyUp(object sender, KeyEventArgs e)
        {
            if (sender != lvGrid) return;

            if (e.Control && e.KeyCode == Keys.C)
                CopySelectedValuesToClipboard();
        }

        private void CopySelectedValuesToClipboard()
        {
            StringBuilder buffer = new StringBuilder();

            for (int i = 0; i < lvGrid.Columns.Count; i++)
            {
                buffer.Append(lvGrid.Columns[i].Text);
                buffer.Append("\t");
            }

            buffer.Append("\n");

            for (int i = 0; i < lvGrid.Items.Count; i++)
            {
                for (int j = 0; j < lvGrid.Columns.Count; j++)
                {
                    buffer.Append(lvGrid.Items[i].SubItems[j].Text);
                    buffer.Append("\t");
                }

                buffer.Append("\n");
            }

            Clipboard.SetText(buffer.ToString());  
        }

Thanks,

Steve

**Comment by rappen** [comment]
Thanks :)
Looking forward to a pull request...!

This is strongly related to #48

**Comment by rappen** [comment]
Solved when closing #63.
