### ISSUE TITLE
FXB error on compiling the project

### ISSUE THREAD

**Issue by umerjaved** [Cinteros/FetchXMLBuilder#99]
Hi,

In order to obtain the executable for the tool, I downloaded the project however getting following error on compiling 

The command "if Debug All Cinteros XTB == Debug xcopy *.dll Plugins /Y
if Debug All Cinteros XTB == Debug xcopy *.pdb Plugins /Y" exited with code 255.	FetchXmlBuilder		
Any help would be appreciated.
Regards

**Comment by rappen** [comment]
Hi,
There is no executable for the tool in this repo. This tool is a plugin to __XrmToolBox__.
Download XrmToolBox exetutable and plugins from http://www.xrmtoolbox.com
Then download FetchXML Builder from http://fxb.xrmtoolbox.com
Do not download source from GitHub unless you plan to develop and enhance the tool :)
